"""
Django settings for internship project.

Generated by 'django-admin startproject' using Django 5.0.
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------------------------------
# ❗ SECURITY
# ------------------------------------------------------

# Keep your secret key (as you requested)
SECRET_KEY = 'django-insecure-ka-&ug=u%n&r0u!nzbsbj+-4ncyxx_n@g!gl-031b*h%c)%o9m'

# Production ready (turn OFF debug)
DEBUG = False

ALLOWED_HOSTS = [
    'fusiontech.onrender.com',
    '127.0.0.1'
]

CSRF_TRUSTED_ORIGINS = [
    'https://fusiontech.onrender.com'
]

# ------------------------------------------------------
# APPLICATIONS
# ------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'fusiontech',
]

# ------------------------------------------------------
# MIDDLEWARE (Added WhiteNoise for production static)
# ------------------------------------------------------

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # WhiteNoise for serving static files on Render
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'internship.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'internship.wsgi.application'

# ------------------------------------------------------
# DATABASE (kept SQLite because you requested no changes)
# ------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ------------------------------------------------------
# PASSWORD VALIDATION
# ------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ------------------------------------------------------
# INTERNATIONALIZATION
# ------------------------------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ------------------------------------------------------
# STATIC FILES (Production)
# ------------------------------------------------------

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise static settings
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ------------------------------------------------------
# EMAIL (kept EXACTLY as you asked)
# ------------------------------------------------------

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'manojrajendrapise@gmail.com'
EMAIL_HOST_PASSWORD = 'abwe evcs rqcf qnqf'

# ------------------------------------------------------
# DEFAULTS
# ------------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
